name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Main Liman Repository
        uses: actions/checkout@v2
        with:
          path: package/liman/server
      - name: Set up Liman Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.3"
          tools: composer
          extensions : ssh2, curl, sqlite3, ldap, mbstring, xml, zip, posix, smbclient, gd
      - name: Build Liman Package
        env:
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          sudo apt install zip gpg curl jq -y
          mkdir -p /home/runner/.gnupg
          echo """
          use-agent
          pinentry-mode   loopback""" | sudo tee -a /home/runner/.gnupg/gpg.conf
          echo "$PRIVATE_KEY" | gpg --import --batch --yes --passphrase $PASSPHRASE

          COMMIT="${GITHUB_REF#refs/heads/} : "
          COMMIT+=`git --git-dir=package/liman/server/.git log -1 --pretty=%B`
          
          sudo chmod +x package/liman/server/.teamcity
          sudo chmod +x package/liman/server/storage/create_deb.sh
          ./package/liman/server/.teamcity $GITHUB_RUN_NUMBER $COMMIT $PASSPHRASE